/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Get$Params as Get$Params } from './fn/events/get';
export { get as get } from './fn/events/get';
export type { Update$Params as Update$Params } from './fn/events/update';
export { update as update } from './fn/events/update';
export type { Delete$Params as Delete$Params } from './fn/events/delete';
export { delete$ as delete$ } from './fn/events/delete';
export type { List$Params as List$Params } from './fn/events/list';
export { list as list } from './fn/events/list';
export type { Create$Params as Create$Params } from './fn/events/create';
export { create as create } from './fn/events/create';
export type { ChangeStatus$Params as ChangeStatus$Params } from './fn/events/change-status';
export { changeStatus as changeStatus } from './fn/events/change-status';
export type { List1$Params as List1$Params } from './fn/bookings/list-1';
export { list1 as list1 } from './fn/bookings/list-1';
export type { Create1$Params as Create1$Params } from './fn/bookings/create-1';
export { create1 as create1 } from './fn/bookings/create-1';
export type { Cancel$Params as Cancel$Params } from './fn/bookings/cancel';
export { cancel as cancel } from './fn/bookings/cancel';
export type { Get1$Params as Get1$Params } from './fn/bookings/get-1';
export { get1 as get1 } from './fn/bookings/get-1';
