/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { BookingRequest } from './models/booking-request';
export type { BookingResponse } from './models/booking-response';
export type { EventRequest } from './models/event-request';
export type { EventResponse } from './models/event-response';
export type { EventStatusRequest } from './models/event-status-request';
export type { Participant } from './models/participant';
