name: arena_mobile
description: "Arena administration mobile application."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.3

dependencies:
  arena_api:
    path: packages/arena_api
  dio: 5.11.1
  flutter:
    sdk: flutter
  flutter_riverpod: 3.4.3
  flutter_appauth: 12.1.0
  flutter_secure_storage: 11.1.1
  nsd: 5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
