/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { BookingResponse } from '../models/booking-response';
import { cancel } from '../fn/bookings/cancel';
import { Cancel$Params } from '../fn/bookings/cancel';
import { create1 } from '../fn/bookings/create-1';
import { Create1$Params } from '../fn/bookings/create-1';
import { get1 } from '../fn/bookings/get-1';
import { Get1$Params } from '../fn/bookings/get-1';
import { list1 } from '../fn/bookings/list-1';
import { List1$Params } from '../fn/bookings/list-1';


/**
 * Personal reservations and administrator booking management
 */
@Injectable({ providedIn: 'root' })
export class BookingsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `list1()` */
  static readonly List1Path = '/api/bookings';

  /**
   * List your bookings; administrators may request scope=all.
   *
   * Defaults to scope=mine, including for administrators. Optional eventId and status filters apply to either scope.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `list1()` instead.
   *
   * This method doesn't expect any request body.
   */
  list1$Response(params?: List1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BookingResponse>>> {
    const obs = list1(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * List your bookings; administrators may request scope=all.
   *
   * Defaults to scope=mine, including for administrators. Optional eventId and status filters apply to either scope.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `list1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  list1(params?: List1$Params, context?: HttpContext): Observable<Array<BookingResponse>> {
    const resp = this.list1$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<BookingResponse>>): Array<BookingResponse> => r.body)
    );
  }

  /** Path part for operation `create1()` */
  static readonly Create1Path = '/api/bookings';

  /**
   * Reserve one place at an event.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create1$Response(params: Create1$Params, context?: HttpContext): Observable<StrictHttpResponse<BookingResponse>> {
    const obs = create1(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Reserve one place at an event.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create1(params: Create1$Params, context?: HttpContext): Observable<BookingResponse> {
    const resp = this.create1$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<BookingResponse>): BookingResponse => r.body)
    );
  }

  /** Path part for operation `cancel()` */
  static readonly CancelPath = '/api/bookings/{id}/cancel';

  /**
   * Cancel a booking as its owner or an administrator before the event starts.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `cancel()` instead.
   *
   * This method doesn't expect any request body.
   */
  cancel$Response(params: Cancel$Params, context?: HttpContext): Observable<StrictHttpResponse<BookingResponse>> {
    const obs = cancel(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Cancel a booking as its owner or an administrator before the event starts.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `cancel$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  cancel(params: Cancel$Params, context?: HttpContext): Observable<BookingResponse> {
    const resp = this.cancel$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<BookingResponse>): BookingResponse => r.body)
    );
  }

  /** Path part for operation `get1()` */
  static readonly Get1Path = '/api/bookings/{id}';

  /**
   * Read a booking as its owner or an administrator.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `get1()` instead.
   *
   * This method doesn't expect any request body.
   */
  get1$Response(params: Get1$Params, context?: HttpContext): Observable<StrictHttpResponse<BookingResponse>> {
    const obs = get1(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Read a booking as its owner or an administrator.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `get1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  get1(params: Get1$Params, context?: HttpContext): Observable<BookingResponse> {
    const resp = this.get1$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<BookingResponse>): BookingResponse => r.body)
    );
  }

}
