/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { changeStatus } from '../fn/events/change-status';
import { ChangeStatus$Params } from '../fn/events/change-status';
import { create } from '../fn/events/create';
import { Create$Params } from '../fn/events/create';
import { delete$ } from '../fn/events/delete';
import { Delete$Params } from '../fn/events/delete';
import { EventPageResponse } from '../models/event-page-response';
import { EventResponse } from '../models/event-response';
import { get } from '../fn/events/get';
import { Get$Params } from '../fn/events/get';
import { list } from '../fn/events/list';
import { List$Params } from '../fn/events/list';
import { update } from '../fn/events/update';
import { Update$Params } from '../fn/events/update';


/**
 * Sports event management
 */
@Injectable({ providedIn: 'root' })
export class EventsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `get()` */
  static readonly GetPath = '/api/events/{id}';

  /**
   * Get event details.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `get()` instead.
   *
   * This method doesn't expect any request body.
   */
  get$Response(params: Get$Params, context?: HttpContext): Observable<StrictHttpResponse<EventResponse>> {
    const obs = get(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Get event details.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `get$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  get(params: Get$Params, context?: HttpContext): Observable<EventResponse> {
    const resp = this.get$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<EventResponse>): EventResponse => r.body)
    );
  }

  /** Path part for operation `update()` */
  static readonly UpdatePath = '/api/events/{id}';

  /**
   * Replace scheduled event details (admin only).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update$Response(params: Update$Params, context?: HttpContext): Observable<StrictHttpResponse<EventResponse>> {
    const obs = update(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Replace scheduled event details (admin only).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update(params: Update$Params, context?: HttpContext): Observable<EventResponse> {
    const resp = this.update$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<EventResponse>): EventResponse => r.body)
    );
  }

  /** Path part for operation `delete()` */
  static readonly DeletePath = '/api/events/{id}';

  /**
   * Delete an event (admin only).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `delete()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete$Response(params: Delete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = delete$(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Delete an event (admin only).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `delete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete(params: Delete$Params, context?: HttpContext): Observable<void> {
    const resp = this.delete$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `list()` */
  static readonly ListPath = '/api/events';

  /**
   * List events, optionally filtering by sport and status.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `list()` instead.
   *
   * This method doesn't expect any request body.
   */
  list$Response(params?: List$Params, context?: HttpContext): Observable<StrictHttpResponse<EventPageResponse>> {
    const obs = list(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * List events, optionally filtering by sport and status.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `list$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  list(params?: List$Params, context?: HttpContext): Observable<EventPageResponse> {
    const resp = this.list$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<EventPageResponse>): EventPageResponse => r.body)
    );
  }

  /** Path part for operation `create()` */
  static readonly CreatePath = '/api/events';

  /**
   * Create a scheduled event (admin only).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create$Response(params: Create$Params, context?: HttpContext): Observable<StrictHttpResponse<EventResponse>> {
    const obs = create(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Create a scheduled event (admin only).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create(params: Create$Params, context?: HttpContext): Observable<EventResponse> {
    const resp = this.create$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<EventResponse>): EventResponse => r.body)
    );
  }

  /** Path part for operation `changeStatus()` */
  static readonly ChangeStatusPath = '/api/events/{id}/status';

  /**
   * Change event status through an allowed lifecycle transition (admin only).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `changeStatus()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  changeStatus$Response(params: ChangeStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<EventResponse>> {
    const obs = changeStatus(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Change event status through an allowed lifecycle transition (admin only).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `changeStatus$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  changeStatus(params: ChangeStatus$Params, context?: HttpContext): Observable<EventResponse> {
    const resp = this.changeStatus$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<EventResponse>): EventResponse => r.body)
    );
  }

}
