/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventResponse } from '../models/event-response';
import { Participant } from '../models/participant';
export interface BookingResponse {
  createdAt: string;
  event: EventResponse;
  id: string;
  participant: Participant;
  status: 'CONFIRMED' | 'CANCELLED';
  updatedAt: string;
}
