/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BookingResponse } from '../models/booking-response';
export interface BookingPageResponse {
  items: Array<BookingResponse>;
  page: number;
  size: number;
  totalElements: number;
  totalPages: number;
}
