/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EventResponse {
  capacity: number;
  createdAt: string;
  description?: (string | null);
  endsAt: string;
  id: string;
  location: string;
  sport: string;
  startsAt: string;
  status: 'SCHEDULED' | 'LIVE' | 'COMPLETED' | 'CANCELLED';
  title: string;
  updatedAt: string;
}
