/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventResponse } from '../models/event-response';
export interface EventPageResponse {
  items: Array<EventResponse>;
  page: number;
  size: number;
  totalElements: number;
  totalPages: number;
}
