/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EventRequest {
  capacity: number;
  description?: string;
  endsAt: string;
  location: string;
  sport: string;
  startsAt: string;
  title: string;
}
