/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BookingResponse } from '../../models/booking-response';

export interface Cancel$Params {
  id: string;
}

export function cancel(http: HttpClient, rootUrl: string, params: Cancel$Params, context?: HttpContext): Observable<StrictHttpResponse<BookingResponse>> {
  const rb = new RequestBuilder(rootUrl, cancel.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BookingResponse>;
    })
  );
}

cancel.PATH = '/api/bookings/{id}/cancel';
